# Generated by Django 5.2.17 on 2026-09-25 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0004_alter_itinerario_id_alter_paquete_id_and_more'),
        ('reservas', '0002_alter_asientoreserva_id_alter_reserva_id'),
        ('usuarios', '0003_alter_agencia_id_alter_rol_id_alter_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='abordado',
            field=models.CharField(default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='asientoreserva',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ChatMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(default='', max_length=400)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('paquete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paquetes.paquete')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'chat_mensajes',
            },
        ),
        migrations.CreateModel(
            name='GpsPunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('velocidad', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paquetes.paquete')),
            ],
            options={
                'db_table': 'gps_puntos',
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='novedad', max_length=80)),
                ('detalle', models.CharField(default='', max_length=400)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('paquete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paquetes.paquete')),
            ],
            options={
                'db_table': 'novedades',
            },
        ),
    ]
