# Generated by Django 6.0.7 on 2026-09-18 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=300)),
                ('duracion_estimada', models.CharField(max_length=50)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField()),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.agencia')),
            ],
            options={
                'db_table': 'paquetes',
            },
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('dia', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(max_length=150)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paquetes.paquete')),
            ],
            options={
                'db_table': 'itinerarios',
            },
        ),
        migrations.CreateModel(
            name='PaqueteDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinos.destino')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paquetes.paquete')),
            ],
            options={
                'db_table': 'paquetes_destino',
            },
        ),
    ]
