# Generated by Django 5.2.17 on 2026-09-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0003_android'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paquetedestino',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Viaje',
        ),
    ]
