# Generated by Django 6.0.7 on 2026-09-18 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('departamento', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'destino',
            },
        ),
        migrations.CreateModel(
            name='Hospedaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=300)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinos.destino')),
            ],
            options={
                'db_table': 'hospedaje',
            },
        ),
        migrations.CreateModel(
            name='ImagenDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_img', models.ImageField(max_length=255, upload_to='')),
                ('descripcion', models.CharField(max_length=255)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinos.destino')),
            ],
            options={
                'db_table': 'imagenes_destino',
            },
        ),
        migrations.CreateModel(
            name='SitioTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=300)),
                ('recomendaciones', models.CharField(max_length=300)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinos.destino')),
            ],
            options={
                'db_table': 'sitio_turistico',
            },
        ),
    ]
