# Generated by Django 5.2.17 on 2026-09-25 00:54 (editado a mano)
import unicodedata

import django.db.models.deletion
from django.db import migrations, models

NOMBRES_DEPARTAMENTOS = [
    "Amazonas", "Antioquia", "Arauca", "Atlántico", "Bolívar", "Boyacá",
    "Caldas", "Caquetá", "Casanare", "Cauca", "Cesar", "Chocó",
    "Cundinamarca", "Córdoba", "Guainía", "Guaviare", "Huila",
    "La Guajira", "Magdalena", "Meta", "Nariño", "Norte de Santander",
    "Putumayo", "Quindío", "Risaralda", "San Andrés y Providencia",
    "Santander", "Sucre", "Tolima", "Valle del Cauca", "Vaupés", "Vichada",
]


def normalizar(texto):
    """quita tildes y pasa a minúsculas para poder comparar 'quindío' con 'Quindío'."""
    texto = (texto or "").strip().lower()
    return "".join(
        c for c in unicodedata.normalize("NFD", texto)
        if unicodedata.category(c) != "Mn"
    )


def poblar_departamentos(apps, schema_editor):
    Departamento = apps.get_model("destinos", "Departamento")
    for nombre in NOMBRES_DEPARTAMENTOS:
        Departamento.objects.get_or_create(nombre=nombre)


def deshacer_poblar_departamentos(apps, schema_editor):
    Departamento = apps.get_model("destinos", "Departamento")
    Departamento.objects.filter(nombre__in=NOMBRES_DEPARTAMENTOS).delete()


def migrar_texto_a_fk(apps, schema_editor):
    Departamento = apps.get_model("destinos", "Departamento")
    por_nombre = {normalizar(d.nombre): d for d in Departamento.objects.all()}

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT id, departamento_id FROM destino")
        filas = cursor.fetchall()

    with schema_editor.connection.cursor() as cursor:
        for destino_id, texto in filas:
            depto = por_nombre.get(normalizar(texto))
            if depto:
                cursor.execute(
                    "UPDATE destino SET departamento_fk_id = %s WHERE id = %s",
                    [depto.id, destino_id],
                )
            else:
                print(f"[AVISO] No se encontró departamento para {texto!r} (destino id={destino_id})")


def deshacer_migrar_texto_a_fk(apps, schema_editor):
    pass  # no reversible de forma segura


def crear_departamento_si_falta(apps, schema_editor):
    schema_editor.execute(
        "CREATE TABLE IF NOT EXISTS `departamento` "
        "(`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, "
        "`nombre` varchar(100) NOT NULL)"
    )


def agregar_fk_si_falta(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        columnas = {
            columna.name
            for columna in schema_editor.connection.introspection.get_table_description(
                cursor, "destino"
            )
        }

    if "departamento_fk_id" not in columnas:
        schema_editor.execute(
            "ALTER TABLE `destino` ADD COLUMN `departamento_fk_id` bigint NULL"
        )

    with schema_editor.connection.cursor() as cursor:
        restricciones = schema_editor.connection.introspection.get_constraints(
            cursor, "destino"
        )

    tiene_fk = any(
        restriccion.get("foreign_key")
        and restriccion["foreign_key"][0] == "departamento"
        for restriccion in restricciones.values()
    )
    if not tiene_fk:
        schema_editor.execute(
            "ALTER TABLE `destino` ADD CONSTRAINT "
            "`destino_departamento_fk_id_a78979be_fk_departamento_id` "
            "FOREIGN KEY (`departamento_fk_id`) REFERENCES `departamento` (`id`)"
        )


def quitar_columna_texto_si_falta(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        columnas = {
            columna.name
            for columna in schema_editor.connection.introspection.get_table_description(
                cursor, "destino"
            )
        }

    if "departamento" in columnas:
        schema_editor.execute("ALTER TABLE `destino` DROP COLUMN `departamento`")
    elif "departamento_id" in columnas and "departamento_fk_id" in columnas:
        schema_editor.execute("ALTER TABLE `destino` DROP COLUMN `departamento_id`")


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0002_alter_destino_id_alter_hospedaje_id_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    crear_departamento_si_falta,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Departamento',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('nombre', models.CharField(max_length=100)),
                    ],
                    options={
                        'db_table': 'departamento',
                    },
                ),
            ],
        ),
        migrations.AlterField(
            model_name='destino',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hospedaje',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imagendestino',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitioturistico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),

        migrations.RunPython(poblar_departamentos, deshacer_poblar_departamentos),

        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    agregar_fk_si_falta,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='destino',
                    name='departamento_fk',
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='destinos.departamento',
                    ),
                ),
            ],
        ),

        migrations.RunPython(migrar_texto_a_fk, deshacer_migrar_texto_a_fk),

        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    quitar_columna_texto_si_falta,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='destino',
                    name='departamento',
                ),
            ],
        ),

        migrations.RenameField(
            model_name='destino',
            old_name='departamento_fk',
            new_name='departamento',
        ),

        migrations.AlterField(
            model_name='destino',
            name='departamento',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='destinos.departamento',
            ),
        ),
    ]
