# Generated by Django 6.1.1 on 2026-09-05 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nit', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=150)),
            ],
            options={
                'db_table': 'agencia',
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asiento', models.IntegerField()),
            ],
            options={
                'db_table': 'asientos',
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('departamento', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'destino',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Hospedaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=300)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospedajes', to='RutaTour.destino')),
            ],
            options={
                'db_table': 'hospedaje',
            },
        ),
        migrations.CreateModel(
            name='ImagenDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_img', models.ImageField(max_length=255, upload_to='')),
                ('descripcion', models.CharField(max_length=255)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='RutaTour.destino')),
            ],
            options={
                'db_table': 'imagenes_destino',
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=300)),
                ('duracion_estimada', models.CharField(max_length=50)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField()),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='RutaTour.agencia')),
            ],
            options={
                'db_table': 'paquetes',
            },
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('dia', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(max_length=150)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerarios', to='RutaTour.paquete')),
            ],
            options={
                'db_table': 'itinerarios',
            },
        ),
        migrations.CreateModel(
            name='PaqueteDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquete_destinos', to='RutaTour.destino')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquete_destinos', to='RutaTour.paquete')),
            ],
            options={
                'db_table': 'paquetes_destino',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField()),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='RutaTour.paquete')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField()),
                ('referencia', models.ImageField(upload_to='')),
                ('comprobante', models.CharField(max_length=255)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('motivo_rechazo', models.CharField(max_length=255)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='RutaTour.reserva')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='AsientoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_asiento', to='RutaTour.asiento')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos_reserva', to='RutaTour.reserva')),
            ],
            options={
                'db_table': 'asientos_reserva',
            },
        ),
        migrations.CreateModel(
            name='SitioTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=300)),
                ('recomendaciones', models.CharField(max_length=300)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitios_turisticos', to='RutaTour.destino')),
            ],
            options={
                'db_table': 'sitio_turistico',
            },
        ),
        migrations.CreateModel(
            name='TipoBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=300)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_bus', to='RutaTour.agencia')),
            ],
            options={
                'db_table': 'tipo_bus',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('fecha_registro', models.DateTimeField()),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='RutaTour.agencia')),
                ('tipo_bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buses', to='RutaTour.tipobus')),
            ],
            options={
                'db_table': 'buses',
            },
        ),
        migrations.AddField(
            model_name='asiento',
            name='tipo_bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='RutaTour.tipobus'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('tipo_documento', models.CharField(max_length=30)),
                ('numero_documento', models.CharField(max_length=30, unique=True)),
                ('correo', models.EmailField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=255)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='RutaTour.agencia')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='RutaTour.rol')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='RutaTour.usuario'),
        ),
    ]
