# Generated by Django 6.1.1 on 2026-09-07 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RutaTour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='tipo_bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RutaTour.tipobus'),
        ),
        migrations.AlterField(
            model_name='asientoreserva',
            name='asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RutaTour.asiento'),
        ),
        migrations.AlterField(
            model_name='asientoreserva',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RutaTour.reserva'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='agencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RutaTour.agencia'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='tipo_bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RutaTour.tipobus'),
        ),
        migrations.AlterField(
            model_name='hospedaje',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RutaTour.destino'),
        ),
        migrations.AlterField(
            model_name='imagendestino',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RutaTour.destino'),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RutaTour.paquete'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RutaTour.reserva'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='agencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RutaTour.agencia'),
        ),
        migrations.AlterField(
            model_name='paquetedestino',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RutaTour.destino'),
        ),
        migrations.AlterField(
            model_name='paquetedestino',
            name='paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RutaTour.paquete'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RutaTour.paquete'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RutaTour.usuario'),
        ),
        migrations.AlterField(
            model_name='sitioturistico',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RutaTour.destino'),
        ),
        migrations.AlterField(
            model_name='tipobus',
            name='agencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RutaTour.agencia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='agencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RutaTour.agencia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RutaTour.rol'),
        ),
    ]
