# Generated by Django 6.0.4 on 2026-09-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RutaTour', '0002_alter_asiento_tipo_bus_alter_asientoreserva_asiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='codigo_confirmacion',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
