# Generated by Django 6.0.7 on 2026-09-18 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=300)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.agencia')),
            ],
            options={
                'db_table': 'tipo_bus',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('fecha_registro', models.DateTimeField()),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.agencia')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
                ('tipo_bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buses.tipobus')),
            ],
            options={
                'db_table': 'buses',
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asiento', models.IntegerField()),
                ('tipo_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buses.tipobus')),
            ],
            options={
                'db_table': 'asientos',
            },
        ),
    ]
