# Generated by Django 6.0.7 on 2026-09-18 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField()),
                ('comprobante', models.ImageField(blank=True, upload_to='')),
                ('referencia', models.CharField(blank=True, default='', max_length=255)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('motivo_rechazo', models.CharField(blank=True, default='', max_length=255)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
    ]
